spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university_test
    username: postgres
    password: prash
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: college

  thymeleaf:
    cache: false

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS college
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        default_schema: college
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
