#spring:
##  profiles:
##      active: dev
#  #    active: loginRunner
#  #    active: studentRunner
#  #    active: branchRunner
#  #    active: sectionRunner
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/university
#    username: postgres
#    password: prasha
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        default_schema: college
#
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#server:
#    port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}          # dynamically points to Railway Postgres :contentReference[oaicite:1]{index=1}
    username: ${PGUSER}                                               # Railway DB user :contentReference[oaicite:2]{index=2}
    password: ${PGPASSWORD}                                           # Railway DB password :contentReference[oaicite:3]{index=3}
    driver-class-name: org.postgresql.Driver                          # standard Postgres driver :contentReference[oaicite:4]{index=4}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect        # unchanged
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: college
server:
  port: ${PORT:8080}                                                 # Railway supplies PORT env var :contentReference[oaicite:5]{index=5}
