spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: ${PORT:8080}
  address: 0.0.0.0  # Add this line to bind to all interfaces

logging:
  level:
    com.university: DEBUG
    org.springframework.web: DEBUG
