spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # default_schema: public  # Optional: Uncomment if you want to specify the schema

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: ${PORT:8080}
