#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/university
#    username: postgres
#    password: prasha
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        default_schema: college